apiVersion: v1
kind: Service
metadata:
  name: sparql-headless-service
spec:
  # selector provided via kustomize
  ports:
    - name: http
      port: 80
      targetPort: 8890
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 60