version: '3.7'
services:
  sparql-virtuoso-updater:
    container_name: sparql-virtuoso-updater
    image: europeana/sparql-virtuoso-updater:latest
    # Only works when Docker compatibility mode is on
    deploy:
      resources:
        limits:
          memory: 16G
    environment:
      # Password should match virtuoso.password in sparql-updater properties file
      DBA_PASSWORD: REMOVED
    ports:
      - published: 8890
        target: 8890
      - published: 1111
        target: 1111
    stdin_open: true
    tty: true
    volumes:
      # We create a folder ./database on the local system thus mimicking the persistent volume in kubernetes deployments
      - ./database:/database
    