checkpoint;

delete from DB.DBA.load_list;

ld_dir ('/opt/virtuoso-opensource/vad', 'edm-v527-160401.owl', 'http://www.europeana.eu/schemas/edm/');

rdf_loader_run();

DB.DBA.XML_REMOVE_NS_BY_PREFIX ('as', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('bif', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('cc', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('data', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('dawgt', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('dbpedia', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('dbpprop', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('dc', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('dcterms', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('doap', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('dqv', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('ebucore', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('edm', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('fn', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('foaf', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('formats', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('geo', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('go', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('gqi', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('gql', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('ldp', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('math', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('mesh', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('mf', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('nci', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('obo', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('odrl', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('ogc', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('ogcgml', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('ogcgs', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('ogcgsf', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('ogcgsr', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('ogcsf', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('ore', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('owl', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('product', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('protseq', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('rdaGr2', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('rdf', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('rdfa', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('rdfdf', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('rdfs', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('sc', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('scovo', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('sd', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('sioc', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('skos', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('sql', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('stat', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('svcs', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('vcard', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('vcard2006', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('virtcxml', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('virtrdf', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('void', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('xf', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('xml', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('xsd', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('xsl10', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('xsl1999', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('xslwd', 2);
DB.DBA.XML_REMOVE_NS_BY_PREFIX ('yago', 2);

DB.DBA.XML_SET_NS_DECL ('cc', 'http://creativecommons.org/ns#', 2);
DB.DBA.XML_SET_NS_DECL ('dc', 'http://purl.org/dc/elements/1.1/', 2);
DB.DBA.XML_SET_NS_DECL ('dcterms', 'http://purl.org/dc/terms/', 2);
DB.DBA.XML_SET_NS_DECL ('dqv', 'http://www.w3.org/ns/dqv#', 2);
DB.DBA.XML_SET_NS_DECL ('ebucore', 'http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#', 2);
DB.DBA.XML_SET_NS_DECL ('edm', 'http://www.europeana.eu/schemas/edm/', 2);
DB.DBA.XML_SET_NS_DECL ('foaf', 'http://xmlns.com/foaf/0.1/', 2);
DB.DBA.XML_SET_NS_DECL ('odrl', 'http://www.w3.org/ns/odrl/2/', 2);
DB.DBA.XML_SET_NS_DECL ('ore', 'http://www.openarchives.org/ore/terms/', 2);
DB.DBA.XML_SET_NS_DECL ('owl', 'http://www.w3.org/2002/07/owl#', 2);
DB.DBA.XML_SET_NS_DECL ('rdaGr2', 'http://rdvocab.info/ElementsGr2/', 2);
DB.DBA.XML_SET_NS_DECL ('rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#', 2);
DB.DBA.XML_SET_NS_DECL ('rdfs', 'http://www.w3.org/2000/01/rdf-schema#', 2);
DB.DBA.XML_SET_NS_DECL ('scvs', 'http://rdfs.org/sioc/services#', 2);
DB.DBA.XML_SET_NS_DECL ('skos', 'http://www.w3.org/2004/02/skos/core#', 2);
DB.DBA.XML_SET_NS_DECL ('xsd', 'http://www.w3.org/2001/XMLSchema#', 2);
DB.DBA.XML_SET_NS_DECL ('wgs84_pos', 'http://www.w3.org/2003/01/geo/wgs84_pos#', 2);

checkpoint;
