# Docker file for running Virtuoso and the sparql-updater

FROM openlink/virtuoso-opensource-7:7.2
LABEL org.opencontainers.image.vendor="Europeana Foundation" \
      org.opencontainers.image.authors="api@europeana.eu" \
      org.opencontainers.image.documentation="https://pro.europeana.eu/page/apis" \
      org.opencontainers.image.source="https://github.com/europeana/sparql-updater" \
      org.opencontainers.image.licenses="EUPL-1.2"

# Install OpenJDK-17
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    apt-get clean;

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/
RUN export JAVA_HOME

# Install Virtuoso config files
COPY ./virtuoso/load-edm.sql /initdb.d/load-edm.sql
COPY ./virtuoso/edm-v527-160401.owl /opt/virtuoso-opensource/vad/edm-v527-160401.owl

# Config for doing updates on server
# ----------------------------------
# Folder /database/tmp-ingest is used to temporarily store files for ingestion so for loading data Virtuoso should be
# configured to have access to that folder
ENV VIRT_Parameters_DirsAllowed=.,../vad,/database/tmp-ingest
# Buffer optimization for 32GB RAM, see also https://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFPerformanceTuning
ENV VIRT_Parameters_NumberOfBuffers=2720000
ENV VIRT_Parameters_MaxDirtyBuffers=2000000

# Install SPARQL updater
COPY ./target/sparql-updater.jar /opt/sparql-updater/sparql-updater.jar

COPY --chmod=777 ./virtuoso/start_virtuoso_and_updater.sh /start_virtuoso_and_updater.sh

EXPOSE 8890
EXPOSE 1111
ENTRYPOINT ["/start_virtuoso_and_updater.sh"]




