apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sparql-statefulset
spec:
  # selector.matchLabels is provided via Kustomize
  template:
    spec:
      containers:
        - name: sparql
          image: europeana/sparql
          ports:
            - containerPort: 8890
          startupProbe:
            httpGet:
              port: 8890
              path: /sparql
            initialDelaySeconds: 10
            # 30 * 10 = 300 seconds, we set this long time on purpose because Virtuoso may need to reapply an open transaction
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              port: 8890
              path: /sparql
            periodSeconds: 20
          readinessProbe:
            httpGet:
              port: 8890
              path: /sparql
            periodSeconds: 20
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/opt/app/config/sparql-updater.user.properties"
          volumeMounts:
            - name: config
              mountPath: "/opt/app/config/sparql-updater.user.properties"
              readOnly: true
              subPath: sparql-updater.user.properties
      volumes:
        - name: config
          configMap:
            name: sparql-updater-config