apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sparql-statefulset
spec:
  # selector.matchLabels is provided via Kustomize
  template:
    spec:
      containers:
        - name: sparql-virtuoso
          image: europeana/sparql-virtuoso
          ports:
            - containerPort: 8890
          env:
            # Note that after 50 seconds any connection in our k8s is automatically terminated
            - name: VIRT_SPARQL_MaxQueryExecutionTime
              value: "45"
