apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sparql-statefulset
spec:
  # selector.matchLabels is provided via Kustomize
  template:
    spec:
      containers:
        - name: sparql
          image: europeana/sparql
          ports:
            - containerPort: 8890
          startupProbe:
            httpGet:
              port: 8890
              path: /sparql
            initialDelaySeconds: 10
            # 12 * 10 sec = 120 seconds, just in case Virtuoso requires much time to start.
            periodSeconds: 10
            failureThreshold: 12
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/opt/app/config/sparql-updater.user.properties"
          volumeMounts:
            - name: config
              mountPath: "/opt/app/config/sparql-updater.user.properties"
              readOnly: true
              subPath: sparql-updater.user.properties
      volumes:
        - name: config
          configMap:
            name: sparql-updater-config