apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app: sparql

# expects files to be in the same directory as this file
configMapGenerator:
  - name: sparql-updater-config
    files:
      - sparql-updater.user.properties
